import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{ArrowDown,ArrowUpRight,BrainCircuit,CheckCircle2,Code2,Database,ExternalLink,Github,GraduationCap,Linkedin,Mail,Menu,X,Smartphone,Terminal,Trophy,Award,Sparkles}from"lucide-react";
import"./styles.css";
const profile={name:"Krishan Kant",role:"CSE (AI & ML) Student",headline:"Aspiring AI/ML Engineer & Software Developer",email:"krishankant882005@gmail.com",github:"https://github.com/krishankant882005-netizen",linkedin:"https://www.linkedin.com/in/krishan-kant-9b8618379"};
const skills=[
{name:"Python",type:"Programming",icon:Code2},{name:"C / C++",type:"Programming",icon:Terminal},{name:"Basic DSA",type:"Problem Solving",icon:BrainCircuit},{name:"SQL",type:"Database",icon:Database},{name:"Git & GitHub",type:"Tools",icon:Github},{name:"Flutter",type:"Development",icon:Smartphone},{name:"Web Development",type:"Development",icon:Code2}];
const projects=[
{number:"01",title:"Campus Circle",category:"Student Community Platform",description:"A campus-focused application concept connecting students for marketplace listings, rentals, rides, study partners, food splitting, fitness partners and community activities.",tags:["Flutter","App Development","UI/UX"]},
{number:"02",title:"Dungeon Quest",category:"Console Adventure Game",description:"A C++ adventure game demonstrating object-oriented programming through dungeon exploration, item collection, enemies, combat and score-based progression.",tags:["C++","OOP","Game"]},
{number:"03",title:"Expression Evaluator",category:"Programming Project",description:"A programming project focused on parsing and evaluating expressions while strengthening fundamentals of algorithms, logic and data structures.",tags:["C++","DSA","Algorithms"]},
{number:"04",title:"Attendance Management System",category:"Software Engineering Project",description:"A structured attendance-management solution developed around requirements, system design, UML/DFD modelling and software engineering practices.",tags:["Software Engineering","UML","System Design"]}];
const education=[
{year:"2025 — 2029",title:"B.Tech — CSE (AI & ML)",place:"Lovely Professional University (LPU)",text:"Currently pursuing a Bachelor of Technology with a focus on computer science, artificial intelligence and machine learning."},
{year:"12th",title:"Senior Secondary Education",place:"LADY A SINGHANIA EDNL ACADEMY JHALAWAR RAJ (10427)",text:"Completed senior secondary education before beginning undergraduate studies."},
{year:"10th",title:"Secondary Education",place:"TINY TOTS ENG MEDIUM SCHOOL TUNDLA FIROZABAD UP (60378)",text:"Completed secondary education and built the academic foundation for further studies."}];
const certificates=["AI Certificate of Accomplishment — Chandigarh University","Course on Computer Concepts (CCC) — NIELIT (NCVET)","Holistic Skill Development Course for Professional Excellence","Google Gemini Certificate","Machine Learning Using Python","Deep Learning Specialization","Saylor certifications","Infosys certifications","Oracle certifications","NPTEL certifications — In Progress"];
const activities=["Participated in a university-level hackathon and collaborated on technology solutions under time constraints.","Competed in coding competitions to strengthen problem-solving and algorithmic thinking.","Completed a 30-hour Communication Skills Course with 2 offline Continuous Assessments.","Actively improving DSA through competitive programming practice."];
const softSkills=["Problem Solving & Critical Thinking","Teamwork & Collaboration","Quick Learner & Adaptable","Leadership Skills","Time Management"];
function App(){const[menuOpen,setMenuOpen]=useState(false);const[active,setActive]=useState("home");useEffect(()=>{const sections=["home","about","skills","projects","education","certificates","contact"];const onScroll=()=>{const point=scrollY+180;let current="home";sections.forEach(id=>{const el=document.getElementById(id);if(el&&el.offsetTop<=point)current=id});setActive(current)};addEventListener("scroll",onScroll);onScroll();return()=>removeEventListener("scroll",onScroll)},[]);const close=()=>setMenuOpen(false);return <div className="site"><div className="noise"/><div className="orb orb-a"/><div className="orb orb-b"/><div className="grid-bg"/>
<header className="nav-wrap"><nav className="navbar"><a href="#home" className="brand" onClick={close}>Krishan Kant</a><div className={`nav-links ${menuOpen?"show":""}`}>{[["home","Home"],["about","About"],["skills","Skills"],["projects","Projects"],["education","Education"],["contact","Contact"]].map(([id,label])=><a key={id} className={active===id?"active":""} href={`#${id}`} onClick={close}>{label}</a>)}</div><a className="nav-cta" href={profile.github} target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={16}/></a><button className="menu-toggle" onClick={()=>setMenuOpen(!menuOpen)}>{menuOpen?<X/>:<Menu/>}</button></nav></header>
<main>
<section id="home" className="hero section"><div className="hero-left reveal"><div className="availability"><span/> Open to learning & opportunities</div><p className="mini-label">HELLO, I'M</p><h1>Krishan<br/><em>Kant.</em></h1><h2>{profile.headline}</h2><p className="hero-description">I build practical projects while strengthening my foundations in programming, software development, data structures and AI/ML.</p><div className="hero-actions"><a className="button primary" href="#projects">Explore my work <ArrowDown size={17}/></a><a className="button ghost" href={`mailto:${profile.email}`}>Let's connect <Mail size={17}/></a></div><div className="socials"><a href={profile.github} target="_blank" rel="noreferrer"><Github/></a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin/></a><a href={`mailto:${profile.email}`}><Mail/></a></div></div><div className="hero-right reveal delay"><div className="profile-frame"><div className="frame-glow"/><div className="portrait-placeholder">
                <img
                  src="/krishan-kant-profile.jpeg"
                  alt="Krishan Kant"
                  className="profile-photo"
                />
              </div><div className="floating-chip chip-one"><Code2 size={16}/> Building</div><div className="floating-chip chip-two"><BrainCircuit size={16}/> AI / ML</div></div></div><a className="scroll-cue" href="#about"><span/> Scroll to explore</a></section>
<section id="about" className="section"><div className="section-title"><span>01</span><div><p>WHO I AM</p><h2>More than just<br/><em>a student.</em></h2></div></div><div className="about-layout"><div className="about-lead"><p>I'm a B.Tech CSE (AI & ML) student at Lovely Professional University, focused on becoming an AI/ML Engineer and Software Engineer.</p><p className="muted">I enjoy learning by building. From C++ console projects to Flutter applications and software engineering systems, every project is a chance to improve my technical foundation.</p></div><div className="about-stats"><div><strong>2029</strong><span>Expected Graduation</span></div><div><strong>04</strong><span>Featured Projects</span></div><div><strong>10+</strong><span>Certifications / Courses</span></div><div><strong>∞</strong><span>Learning Mindset</span></div></div></div></section>
<section id="skills" className="section"><div className="section-title compact"><span>02</span><div><p>WHAT I WORK WITH</p><h2>Skills & <em>tools.</em></h2></div></div><div className="skills-grid">{skills.map(({name,type,icon:Icon})=><div className="skill-card" key={name}><div className="skill-icon"><Icon size={22}/></div><div><span>{type}</span><h3>{name}</h3></div><ArrowUpRight className="skill-arrow" size={18}/></div>)}</div><div className="soft-wrap"><span className="soft-label">SOFT SKILLS</span><div className="soft-list">{softSkills.map(s=><span key={s}>{s}</span>)}</div></div></section>
<section id="projects" className="section"><div className="section-title compact"><span>03</span><div><p>SELECTED WORK</p><h2>Things I've <em>built.</em></h2></div></div><div className="project-list">{projects.map(p=><article className="project-row" key={p.title}><div className="project-index">{p.number}</div><div className="project-main"><span>{p.category}</span><h3>{p.title}</h3><p>{p.description}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></div><a href={profile.github} target="_blank" rel="noreferrer" className="project-link"><ExternalLink size={20}/></a></article>)}</div></section>
<section id="education" className="section"><div className="section-title compact"><span>04</span><div><p>MY JOURNEY</p><h2>Education & <em>growth.</em></h2></div></div><div className="timeline">{education.map((item,i)=><div className="timeline-item" key={item.title}><div className="timeline-dot">{i===0?<GraduationCap size={17}/>:<CheckCircle2 size={17}/>}</div><div className="timeline-year">{item.year}</div><div className="timeline-content"><h3>{item.title}</h3><strong>{item.place}</strong><p>{item.text}</p></div></div>)}</div><div className="activity-box"><div className="activity-head"><Trophy size={22}/><div><span>ACHIEVEMENTS & ACTIVITIES</span><h3>Learning beyond the classroom.</h3></div></div><div className="activity-grid">{activities.map((a,i)=><div key={a}><b>0{i+1}</b><p>{a}</p></div>)}</div></div></section>
<section id="certificates" className="section"><div className="section-title compact"><span>05</span><div><p>CONTINUOUS LEARNING</p><h2>Certificates & <em>courses.</em></h2></div></div><div className="certificate-grid">{certificates.map((cert,i)=><div className="certificate-card" key={cert}><span>0{(i%9)+1}</span><Award size={20}/><p>{cert}</p></div>)}</div></section>
<section id="contact" className="section contact-section"><div className="contact-card"><div className="contact-kicker"><Sparkles size={15}/> LET'S BUILD SOMETHING</div><h2>Have an idea?<br/><em>Let's make it real.</em></h2><p>I'm open to learning, collaborating and working on interesting software and AI/ML projects.</p><a className="button primary" href={`mailto:${profile.email}`}>Start a conversation <Mail size={17}/></a><div className="contact-links"><a href={profile.github} target="_blank" rel="noreferrer"><Github size={17}/> GitHub</a><a href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={17}/> LinkedIn</a><a href={`mailto:${profile.email}`}><Mail size={17}/> Email</a></div></div></section>
</main><footer><div><span className="brand small">Krishan Kant</span><p>Designed & built by {profile.name}</p></div><p>© 2026 — Learning, building, growing.</p></footer></div>}
createRoot(document.getElementById("root")).render(<App/>);
